apiVersion: v1
kind: ConfigMap
metadata:
  name: reports-configmap
  namespace: tombo
  labels:
    app.kubernetes.io/name: reports-configmap
    app.kubernetes.io/component: configmap
    app.kubernetes.io/part-of: tombo
data:
  REDIS_URL: "redis://tombo-redis-master:6379"
  GOOGLE_CLIENT_ID: ${REPORTS_GOOGLE_CLIENT_ID}
