apiVersion: v1
kind: Secret
metadata:
  name: reports-secrets
  namespace: tombo
  labels:
    app.kubernetes.io/name: reports-secrets
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: tombo
type: Opaque
stringData:
  POSTGRES_USER: ${REPORTS_POSTGRES_USER}
  POSTGRES_PASSWORD: ${REPORTS_POSTGRES_PASSWORD}
  POSTGRES_DB: ${REPORTS_POSTGRES_DB}
  DATABASE_URL: ${REPORTS_DATABASE_URL}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
