name: "Kubectl setup"
description: "Setup kubectl for running kubectl commands"

inputs:
  commands:
    required: true
    description: kubectl commands to run
  kubeconfig:
    required: true
    description: base64 encoded kubeconfig file

runs:
  using: composite
  steps:
    - name: Install kubectl
      uses: azure/setup-kubectl@v4
      id: install-kubectl
      with:
        version: latest
    - name: Authenticate to the cluster
      shell: bash
      run: |
        echo ${KUBECONFIG} | base64 --decode > kubeconfig
      env:
        KUBECONFIG: ${{ inputs.kubeconfig }}
    - name: Run kubectl commands
      shell: bash
      run: ${{ inputs.commands }}
      env:
        KUBECONFIG: kubeconfig
