services:
  tombodb:
    image: postgis/postgis:latest
    container_name: tombo-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  report-service:
    container_name: report-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    env_file:
      - .env
    depends_on:
      - tombodb
      - redis

volumes:
  postgres-data:
  redis-data:
