services:
  tombodb:
    image: postgres:17.2
    container_name: tombo-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  report-service:
    container_name: report-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    env_file:
      - .env
    depends_on:
      tombodb:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres-data:
  redis-data:
