apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: tombo
  labels:
    app.kubernetes.io/name: minio-secrets
    app.kubernetes.io/component: minio
    app.kubernetes.io/part-of: tombo
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "minio"
  MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
