apiVersion: v1
kind: Secret
metadata:
  name: tombo-secrets
  namespace: tombo
  labels:
    app.kubernetes.io/name: tombo-secrets
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: tombo
type: Opaque
stringData:
  GITHUB_TOKEN: ${GITHUB_TOKEN}
