apiVersion: v1
kind: Secret
metadata:
  name: notifications-secrets
  namespace: tombo
  labels:
    app.kubernetes.io/name: notifications-secrets
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: tombo
stringData:
  ONE_SIGNAL_API_KEY: ${NOTIFICATIONS_ONE_SIGNAL_API_KEY}
