on:
  push:
    branches:
      - main
    paths:
      - 'k8s/manifest/base/**'
      - '.github/workflows/base.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Apply base manifests
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare base/secrets.yml
        uses: danielr1996/envsubst-action@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          input: k8s/manifest/base/secrets.tmpl.yml
          output: k8s/manifest/base/secrets.yml

      - name: Prepare base/cert-issuer.yml
        uses: danielr1996/envsubst-action@1.0.0
        env:
          CERT_MANAGER_EMAIL: ${{ vars.CERT_MANAGER_EMAIL }}
        with:
          input: k8s/manifest/base/cert-issuer.tmpl.yml
          output: k8s/manifest/base/cert-issuer.yml

      - name: Apply base manifests
        uses: ./.github/actions/kubectl
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          commands: |
            kubectl apply -f k8s/manifest/base/namespace.yml
            kubectl apply -f k8s/manifest/base/secrets.yml
            kubectl apply -f k8s/manifest/base/cert-issuer.yml
