on:
  push:
    branches:
      - main
    paths:
      - 'k8s/manifest/base/**'
      - '.github/workflows/base.yml'

jobs:
  deploy:
    name: Apply base manifests
    uses: ./.github/workflows/kubectl.yml
    with:
      commands: |
        kubectl apply -f k8s/manifest/base/namespace.yml
    secrets: inherit
