on:
  workflow_call:
    inputs:
      image:
        required: true
        description: Docker image to deploy to ghcr.io
        type: string
      labels:
        required: true
        description: Docker image labels
        type: string
      dockerfile:
        required: true
        description: Path to Dockerfile
        type: string
      context:
        required: true
        description: Path to build context
        type: string

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ inputs.image }}
          tags: |
            type=sha,format=short
            type=sha,format=long
            type=raw,value=latest
          labels: ${{ inputs.labels }}
      - name: Build and push image
        uses: docker/build-push-action@v6.13.0
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
