on:
  workflow_call:
    inputs:
      commands:
        required: true
        description: kubectl commands to run
        type: string

jobs:
  kubectl:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        id: install-kubectl
        with:
          version: latest
      - name: Authenticate to the cluster
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig
      - name: Check if cluster connection is working
        run: ${{ inputs.commands }}
        env:
          KUBECONFIG: kubeconfig
