on:
  push:
    branches:
      - main
    paths:
      - 'reports-service/**'
      - '.github/workflows/reports.yml'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/ghcr-push.yml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      context: reports-service
      dockerfile: reports-service/Dockerfile
      image: ${{ github.repository }}-reports
      labels: |
        org.opencontainers.image.title=Tombo Reports
        org.opencontainers.image.description=Tombo Reports Microservice

  deploy:
    name: Deploy Reports manifests
    uses: ./.github/workflows/kubectl.yml
    needs: build
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      commands: |
        kubectl cluster-info
