on:
  push:
    branches:
      - main
    paths:
      - 'reports-service/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-reports

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=Tombo Reports
            org.opencontainers.image.description=Tombo Reports Microservice
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: reports-service
          file: reports-service/Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        id: install-kubectl
      - name: Authenticate to the cluster
        run: |
          export KUBECONFIG=${{ secrets.KUBECONFIG }}
      - name: Check if cluster connection is working
        run: |
          kubectl cluster-info
